### PR TITLE
Update to ScummVM 1.10git

### PR DESCRIPTION
**Pull request by RobLoach**
Broken....

```
retroarch: symbol lookup error: scummvm/backends/platform/libretro/build/scummvm_libretro.so: undefined symbol: _ZN19POSIXFilesystemNodeC1ERKN6Common6StringE
```

### CODE REVIEW

**Comment by NelsonRosenberg** [comment]
Is the libretro build still broken? Is it a problem with libretro or scummvm?

**Comment by RobLoach** [comment]
Issue still persists with the libretro core...

```
[INFO] [GL]: VSync => on
[INFO] [GLX]: glXSwapInterval(1)
[INFO] [PulseAudio]: Unpausing.
retroarch: symbol lookup error: scummvm_libretro.so: undefined symbol: _ZN19POSIXFilesystemNodeC1ERKN6Common6StringE
```

**Comment by fetzerch** [comment]
@RobLoach Mind testing https://github.com/fetzerch/scummvm/tree/libretro_v2.0.0 a bit? My plan would be to update and create a PR once 2.0.0 final is released. (hopefully within a month according to the release schedule).

**Comment by RobLoach** [comment]
@fetzerch Nicely done! I'll check it out :+1:

**Comment by RobLoach** [comment]
Was able to run Gabriel Knight :+1: 

screenshot at 2017-11-25 12-18-10

**Comment by NelsonRosenberg** [comment]
Thanks @fetzerch ! Waiting anxiously for a build!

**Comment by fetzerch** [comment]
Thanks for testing! See: https://github.com/libretro/scummvm/pull/85

**Pull request closed without merging**
